export const items = [
  {
    id: 1,
    name: "Dumbbells",
    description: "Set of dumbbells for strength training.",
    price: "$29.99",
    image: "dumbbell.webp",
   describe:"Discover our premium dumbbells for all fitness levels. From adjustable sets to classic iron, find the perfect weights to elevate your workout routine. Shop now for strength, versatility, and results!",
    category: "Strength Training",
  },
  
  {
    id: 2,
    name: "Kettlebell",
    description: "Cast iron kettlebell for strength and conditioning.",
    price: "$34.99",
    image: "Kettlebell.webp",
    category: "Strength Training",
  },
  {
    id: 3,
    name: "Exercise Ball",
    description: "Anti-burst exercise ball for core workouts.",
    price: "$19.99",
    image: "exercise_ball.webp",
    category: "Core & Balance",
  },
 
  {
    id: 4,
    name: "Running Shoes",
    description: "Lightweight running shoes for speed and comfort.",
    price: "$49.99",
    image: "running_shoes.webp",
    category: "Running & Jogging",
  },
   
    {
      id: 5,
      name: "Resistance Bands",
      description: "Set of resistance bands for a full-body workout.",
      price: "$14.99",
      image: "resistance-band.webp",
      category: "Strength Training",
    },
    {
      id: 6,
      name: "Jump Rope",
      description: "Durable jump rope for cardio workouts.",
      price: "$9.99",
      image: "jump_rope.webp",
      category: "Cardio",
    },

    {
      id: 7,
      name: "Resistance Tubes",
      description: "Set of resistance tubes with handles for various exercises.",
      price: "$17.99",
      image: "resistance_tubes.webp",
      category: "Strength Training",
    },
    {
      id: 8,
      name: "Treadmill",
      description: "Foldable treadmill with multiple speed options.",
      price: "$499.99",
      image: "treadmill.webp",
      category: "Cardio",
    },

    {
        id:9,
        name: "Running Jacket",
        description: "Waterproof and breathable running jacket.",
        price: "$39.99",
        image: "running_jacket.webp",
        category: "Running & Jogging",
      },
      {
        id: 10,
        name: "Running Shorts",
        description: "Quick-dry running shorts with built-in briefs.",
        price: "$19.99",
        image: "running_shorts.webp",
        category: "Running & Jogging",
      },
      {
        id: 11,
        name: "Running Belt",
        description: "Adjustable running belt with multiple pockets.",
        price: "$14.99",
        image: "running_belt.webp",
        category: "Running & Jogging",
      },
      {
        id: 12,
        name: "Balance Board",
        description: "Wooden balance board for improving core strength and stability.",
        price: "$29.99",
        image: "balance_board.webp",
        category: "Core & Balance",
      },
      {
        id: 13,
        name: "Skipping Rope",
        description: "Adjustable skipping rope for cardio and endurance training.",
        price: "$7.99",
        image: "skipping_rope.webp",
        category: "Cardio",
      },
      {
        id: 14,
        name: "Stationary Bike",
        description: "Indoor stationary bike for effective cardio workouts.",
        price: "$299.99",
        image: "stationary_bike.webp",
        category: "Cardio",
      },
      {
        id: 15,
        name: "Foam Roller",
        description: "High-density foam roller for muscle recovery.",
        price: "$24.99",
        image: "foam_roller.webp",
        category: "Core & Balance",
      },
    
     
    ];